server:
  port: 8081

spring:
  jpa:
    # \u6307\u5B9A\u662F\u5426\u5728spring\u5BB9\u5668\u542F\u52A8\u65F6\u5019\u521B\u5EFA\u8868\uFF0C\u9ED8\u8BA4\u4E3Afalse
    generate-ddl: true
    # \u6307\u5B9A\u662F\u5426\u5728\u63A7\u5236\u53F0\u663E\u793Asql
    show-sql: true
    # \u6307\u5B9A\u5E94\u7528\u91CD\u542F\u65F6\u5019\u4E0D\u91CD\u65B0\u66F4\u65B0\u8868
    hibernate:
      ddl-auto: none
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.12/test?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: 123456

logging:
  pattern:
    console: level-%level %msg%n
  level:
    # \u63A7\u5236spring boot\u542F\u52A8\u65F6\u5019\u663E\u793A\u7684\u65E5\u5FD7\u7EA7\u522B
    root: info
    # \u63A7\u5236\u81EA\u5DF1\u7684\u4EE3\u7801\u8FD0\u884C\u65F6\u663E\u793A\u7684\u65E5\u5FD7\u7EA7\u522B
    com.abc: debug
    # \u63A7\u5236hibernate\u8FD0\u884C\u65F6\u5019\u7684\u65E5\u5FD7\u7EA7\u522B
    org.hibernate: info
    # \u5728show-sql\u4E3Atrue\u65F6\u5019\u663E\u793ASQL\u4E2D\u7684\u52A8\u6001\u53C2\u6570\u503C
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    # \u5728show-sql\u4E3Atrue\u65F6\u663E\u793A\u67E5\u8BE2\u7ED3\u679C
    org.hibernate.type.descriptor.sql.BasicExtractor: trace

